// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7xMi6bdidwtr6qquhtMR3KUJ9MgQhTFU',
    appId: '1:937894405113:web:75b57b529ec0b46ea2d328',
    messagingSenderId: '937894405113',
    projectId: 'hi-class-factory',
    authDomain: 'hi-class-factory.firebaseapp.com',
    storageBucket: 'hi-class-factory.firebasestorage.app',
    measurementId: 'G-QZ2P2HEP68',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAt6gUeD5BtOBpn5_Wz4UVu6VdbCr9NYMI',
    appId: '1:937894405113:android:7a5035cfa75a618ea2d328',
    messagingSenderId: '937894405113',
    projectId: 'hi-class-factory',
    storageBucket: 'hi-class-factory.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4kItbeR_iZvWDxxvybd6oZcFj3Scqh2Y',
    appId: '1:937894405113:ios:f4c384c85e29ac19a2d328',
    messagingSenderId: '937894405113',
    projectId: 'hi-class-factory',
    storageBucket: 'hi-class-factory.firebasestorage.app',
    iosBundleId: 'com.example.hiClassFactory',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4kItbeR_iZvWDxxvybd6oZcFj3Scqh2Y',
    appId: '1:937894405113:ios:f4c384c85e29ac19a2d328',
    messagingSenderId: '937894405113',
    projectId: 'hi-class-factory',
    storageBucket: 'hi-class-factory.firebasestorage.app',
    iosBundleId: 'com.example.hiClassFactory',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7xMi6bdidwtr6qquhtMR3KUJ9MgQhTFU',
    appId: '1:937894405113:web:7f21c447a7ce4717a2d328',
    messagingSenderId: '937894405113',
    projectId: 'hi-class-factory',
    authDomain: 'hi-class-factory.firebaseapp.com',
    storageBucket: 'hi-class-factory.firebasestorage.app',
    measurementId: 'G-9JH86VS6WH',
  );
}
